package dsl

import (
	"fmt"
	"os"
	"strings"

	yaml "github.com/goccy/go-yaml"
)

type StepType string

const (
	StepTypeExec  StepType = "exec"
	StepTypeSleep StepType = "sleep"
)

// Workflow and Step definitions for YAML parsing
type Workflow struct {
	Name        string  `yaml:"name"`
	Description string  `yaml:"description,omitempty"`
	Stages      []Stage `yaml:"stages"`
}

type Stage struct {
	Name        string `yaml:"name"`
	Description string `yaml:"description,omitempty"`
	Steps       []Step `yaml:"steps"`
}

type Step struct {
	Name        string   `yaml:"name"`
	Description string   `yaml:"description,omitempty"`
	Type        StepType `yaml:"type"`
	Run         []string `yaml:"run,omitempty"`
	Seconds     int      `yaml:"seconds,omitempty"`
}

// LoadWorkflowFromFile loads a Workflow from a YAML file
func LoadWorkflowFromFile(filename string) (*Workflow, error) {
	data, err := os.ReadFile(filename)
	if err != nil {
		return nil, err
	}

	// Normalize tabs to spaces to avoid YAML parsing issues
	if strings.Contains(string(data), "\t") {
		fmt.Printf("Warning: Tabs detected in %s, normalizing to spaces for YAML parsing\n", filename)
	}

	data = normalizeTabs(data)

	var wf Workflow
	if err := yaml.Unmarshal(data, &wf); err != nil {
		return nil, err
	}

	if err := wf.Validate(); err != nil {
		return nil, fmt.Errorf("workflow validation failed: %w", err)
	}

	return &wf, nil
}

// WriteTemplate creates a sample workflow template file
func WriteTemplate(filename string) error {
	tpl, err := minimalWorkflowExample()
	if err != nil {
		return err
	}
	return os.WriteFile(filename, []byte(tpl), 0644)
}

// Normalize tabs to spaces in file content to improve ux and avoid yaml parsing issues
func normalizeTabs(data []byte) []byte {
	normalized := strings.ReplaceAll(string(data), "\t", "  ")
	return []byte(normalized)
}

// MinimalWorkflowExample returns a minimal example workflow in YAML format
func minimalWorkflowExample() (string, error) {
	wf := Workflow{
		Name:        "example-forge-workflow",
		Description: "Generated by forge init",
		Stages: []Stage{
			{
				Name:        "hello-stage",
				Description: "A very simple Stage with two steps",
				Steps: []Step{
					{
						Name: "hello",
						Type: StepTypeExec,
						Run:  []string{"echo", "Hello from Forge"},
					},
					{
						Name:    "pause",
						Type:    StepTypeSleep,
						Seconds: 1,
					},
				},
			},
			{
				Name:        "goodbye-stage",
				Description: "A second Stage to say goodbye",
				Steps: []Step{
					{
						Name: "goodbye",
						Type: StepTypeExec,
						Run:  []string{"echo", "Goodbye from Forge"},
					},
				},
			},
		},
	}
	b, err := yaml.Marshal(&wf)
	if err != nil {
		return "", fmt.Errorf("Failed to generate a minimal workflow example: %w", err)
	}
	return "# Example Workflow YAML\n" + string(b), nil
}
